
export const DataList = [

    {
        id:1,
        store:'Manyavarr',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accept',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Verified',
        category:'Cloth',
        date:'04-02/2022',
        name:'Jeans',
        image:'images/b1.jpg',
        price:1200,
        executive:'James',
        exeimg:'images/exe1.jpeg',
        progresh:'Progressing',
    },


    {
        id:2,
        store:'Apple Store',
        addresh:'Delhi',
        Mobiile:9875444445,
        Status:'Accept',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Axis Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:' Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1900,
        executive:'Michel',
        exeimg:'images/exe2.jpeg',
        progresh:'On Hold',
    },

    {
        id:3,
        store:'Zara',
        addresh:'Hydrabad',
        Mobiile:9875444445,
        Status:'Decline',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'HDFC Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Verified',
        category:'Cloth',
        date:'04-02/2022',
        name:'tshort',
        image:'images/tshort.jpg',
        price:800,
        executive:'David',
        exeimg:'images/exe3.jpeg',
        progresh:'Progressing',
    },

    {
        id:4,
        store:'Samsung Store',
        addresh:'Mumbai',
        Mobiile:9875444445,
        Status:'Accept',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'Mobile',
        image:'images/mobile.jpg',
        price:1900,
        executive:'Chrish',
        exeimg:'images/exe4.jpeg',
        progresh:'Rejected',
    },

    {
        id:5,
        store:'Fashion Store',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accept',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:' Not Verified',
        category:'Cloth',
        date:'04-02/2022',
        name:'Blzer',
        image:'images/b1.jpg',
        price:1400,
        executive:'Finch',
        exeimg:'images/exe5.jpeg',
        progresh:'Progressing',
    },

    {
        id:6,
        store:'Puma',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Decline',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Verified',
        category:'Foot Wear',
        date:'04-02/2022',
        name:'Shoes',
        image:'images/shoes.jpg',
        price:700,
        executive:'Morgan',
        exeimg:'images/exe4.jpeg',
        progresh:'Progressing',
    },
    {
        id:7,
        store:'Apple Store',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Decline',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },

    {
        id:8,
        store:'Samsung Store',
        addresh:'Delhi',
        Mobiile:9875444445,
        Status:'Decline',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },

    {
        id:9,
        store:'Unkonw Store',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accepted',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },
    {
        id:10,
        store:'mystore',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accepted',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },
    {
        id:11,
        store:'your store',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accepted',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },
    {
        id:12,
        store:'Unkonw Store',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accepted',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },
    {
        id:13,
        store:'justdo',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accepted',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },
    {
        id:14,
        store:'Manyabar',
        addresh:'Bangalore',
        Mobiile:9875444445,
        Status:'Accepted',
        AltPhone:'792581670',
        email:'unknown123@gmail.com',
        bank:'Kotak Bank',
        Holder:'ABCDEF',
        ifsc:'ktok9887',
        exestatus:'Not Verified',
        category:'Electronics',
        date:'04-02/2022',
        name:'MacBook',
        image:'images/laptop.jpg',
        price:1800,
        executive:'James',
        exeimg:'images/exe2.jpeg',
        progresh:'Success',
    },

];